# Generated by Django 4.0.1 on 2022-12-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=13, verbose_name='Comment ID')),
                ('content', models.TextField(max_length=50, verbose_name='Content')),
                ('time_commented', models.DateField(blank=True, null=True, verbose_name='Time of commenting')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.CharField(max_length=20, verbose_name='Like ID')),
                ('time_liked', models.DateField(blank=True, null=True, verbose_name='Time of liking')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('location', models.CharField(max_length=40, verbose_name='User location')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=30, verbose_name='Profile name')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Profile avatar')),
                ('description', models.TextField(max_length=50, verbose_name='Profile description')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='main.Profile')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Profile owner')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=14, verbose_name='Post ID')),
                ('content', models.CharField(max_length=300, verbose_name='Content')),
                ('time_posted', models.DateField(blank=True, null=True, verbose_name='Time of posting')),
                ('comments', models.ManyToManyField(to='main.Comment', verbose_name='Comments')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Created by')),
                ('likes', models.ManyToManyField(to='main.Like', verbose_name='Liked by')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Like by'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Commented by'),
        ),
    ]
